name: Sync To Notion

on: [push, ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository.
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install Dependencies
        run: |
            python3 --version
            python3 -m pip install -U pip
            pip3 install requests bibtexparser

      - name: Get latest commit hash
        id: get_commit
        run: echo "LATEST_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Sync to notion
        run: python sync.py
        env:
          NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
          DATABASE_IDENTIFIER: ${{secrets.DATABASE_IDENTIFIER}}
          LATEST_COMMIT: ${{ env.LATEST_COMMIT }}

      - name: Update archive
        run: |
            git config --global user.email "seba-1511@hotmail.com"
            git config --global user.name "Paperpile to Notion"
            if [ -n "$(git status --porcelain)" ]; then
              git add .
              git commit -am 'Update archive.'
            else
              echo "No changes to commit."
            fi
        shell: bash

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}